//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinterEngine.Toolset.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceType
    {
        public long ResourceTypeID { get; set; }
        public string Name { get; set; }
    }
}
