// <autogenerated>
//   This file was generated by T4 code generator ViewModelGenerator.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


var ContentPackage = function()
{
	var self = this;

	//	Type of the original .NET model. Must stay first ! (required for JSON.NET)
	self.$type = 'WinterEngine.DataTransferObjects.ContentPackage, WinterEngine.DataTransferObjects';

	self.FileName = ko.observable();
	self.Description = ko.observable();
	self.ResourceList = ko.observableArray();
	self.ResourceID = ko.observable();
	self.Name = ko.observable();
	self.ResourceTypeID = ko.observable();
	self.ResourceType = ko.observable();
	self.Comment = ko.observable();
	self.IsSystemResource = ko.observable();
	self.CreateDate = ko.observable();

	//	invoke the extendable's init() function. Must happen when all observables are created (in case a
    //	computable wants to make use of it)
    this.init();

    self.setModel = function(objFromServer) {
	  if (!objFromServer) return;

	  self.FileName(objFromServer.FileName);
	  self.Description(objFromServer.Description);
	  self.ResourceList.removeAll();	// clear array first
	  if (objFromServer.ResourceList && objFromServer.ResourceList.length > 0)
	  {
		  for (var i=0; i < objFromServer.ResourceList.length; i++) {
			  var _iter_item = objFromServer.ResourceList[i];
			  				  var _new_item = new ContentPackageResource();
				  _new_item.setModel(_iter_item);
				  self.ResourceList.push(_new_item);
			  		  }
	  }
	  self.ResourceID(objFromServer.ResourceID);
	  self.Name(objFromServer.Name);
	  self.ResourceTypeID(objFromServer.ResourceTypeID);
	  if (objFromServer.ResourceType) {
        var __ResourceType = new ResourceTypeEnum();
	    __ResourceType.setModel(objFromServer.ResourceType);
	    self.ResourceType(__ResourceType);
	  }
	  else
		self.ResourceType(null);
	  self.Comment(objFromServer.Comment);
	  self.IsSystemResource(objFromServer.IsSystemResource);
	  if (objFromServer.CreateDate)
		self.CreateDate(moment(objFromServer.CreateDate).toDate());
	  else
	    self.CreateDate(null);
	  
	  //	check if change tracking is active for this viewmodel. If it is: reset isDirty flag
	  if (self.isDirty)
		  self.isDirty(false);
    }
}

//	inherit from extendable (will allow adding observables/computables on client-side)
ContentPackage.prototype = new extendable();

