// <autogenerated>
//   This file was generated by T4 code generator ViewModelGenerator.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


var ContentPackageResourceXML = function()
{
	var self = this;

	//	Type of the original .NET model. Must stay first ! (required for JSON.NET)
	self.$type = 'WinterEngine.DataTransferObjects.XMLObjects.ContentPackageResourceXML, WinterEngine.DataTransferObjects';

	self.FilePath = ko.observable();
	self.FileName = ko.observable();
	self.ResourceType = ko.observable();
	self.IsInPackage = ko.observable();

	//	invoke the extendable's init() function. Must happen when all observables are created (in case a
    //	computable wants to make use of it)
    this.init();

    self.setModel = function(objFromServer) {
	  if (!objFromServer) return;

	  self.FilePath(objFromServer.FilePath);
	  self.FileName(objFromServer.FileName);
	  if (objFromServer.ResourceType) {
        var __ResourceType = new ContentPackageResourceTypeEnum();
	    __ResourceType.setModel(objFromServer.ResourceType);
	    self.ResourceType(__ResourceType);
	  }
	  else
		self.ResourceType(null);
	  self.IsInPackage(objFromServer.IsInPackage);
	  
	  //	check if change tracking is active for this viewmodel. If it is: reset isDirty flag
	  if (self.isDirty)
		  self.isDirty(false);
    }
}

//	inherit from extendable (will allow adding observables/computables on client-side)
ContentPackageResourceXML.prototype = new extendable();

