// <autogenerated>
//   This file was generated by T4 code generator ViewModelGenerator.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


var GameModule = function()
{
	var self = this;

	//	Type of the original .NET model. Must stay first ! (required for JSON.NET)
	self.$type = 'WinterEngine.DataTransferObjects.GameModule, WinterEngine.DataTransferObjects';

	self.ModuleID = ko.observable();
	self.ModuleTag = ko.observable();
	self.ModuleName = ko.observable();
	self.Description = ko.observable();
	self.Comment = ko.observable();
	self.MaxLevel = ko.observable();
	self.FileName = ko.observable();

	//	invoke the extendable's init() function. Must happen when all observables are created (in case a
    //	computable wants to make use of it)
    this.init();

    self.setModel = function(objFromServer) {
	  if (!objFromServer) return;

	  self.ModuleID(objFromServer.ModuleID);
	  self.ModuleTag(objFromServer.ModuleTag);
	  self.ModuleName(objFromServer.ModuleName);
	  self.Description(objFromServer.Description);
	  self.Comment(objFromServer.Comment);
	  self.MaxLevel(objFromServer.MaxLevel);
	  self.FileName(objFromServer.FileName);
	  
	  //	check if change tracking is active for this viewmodel. If it is: reset isDirty flag
	  if (self.isDirty)
		  self.isDirty(false);
    }
}

//	inherit from extendable (will allow adding observables/computables on client-side)
GameModule.prototype = new extendable();

