// <autogenerated>
//   This file was generated by T4 code generator ViewModelGenerator.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


var UserProfile = function()
{
	var self = this;

	//	Type of the original .NET model. Must stay first ! (required for JSON.NET)
	self.$type = 'WinterEngine.DataTransferObjects.BusinessObjects.UserProfile, WinterEngine.DataTransferObjects';

	self.UserID = ko.observable();
	self.UserName = ko.observable();
	self.UserPassword = ko.observable();
	self.UserEmail = ko.observable();
	self.UserFirstName = ko.observable();
	self.UserLastName = ko.observable();
	self.UserDOB = ko.observable();
	self.IsEmailVerified = ko.observable();
	self.IsLoggedIn = ko.observable();

	//	invoke the extendable's init() function. Must happen when all observables are created (in case a
    //	computable wants to make use of it)
    this.init();

    self.setModel = function(objFromServer) {
	  if (!objFromServer) return;

	  self.UserID(objFromServer.UserID);
	  self.UserName(objFromServer.UserName);
	  self.UserPassword(objFromServer.UserPassword);
	  self.UserEmail(objFromServer.UserEmail);
	  self.UserFirstName(objFromServer.UserFirstName);
	  self.UserLastName(objFromServer.UserLastName);
	  if (objFromServer.UserDOB)
		self.UserDOB(moment(objFromServer.UserDOB).toDate());
	  else
	    self.UserDOB(null);
	  self.IsEmailVerified(objFromServer.IsEmailVerified);
	  self.IsLoggedIn(objFromServer.IsLoggedIn);
	  
	  //	check if change tracking is active for this viewmodel. If it is: reset isDirty flag
	  if (self.isDirty)
		  self.isDirty(false);
    }
}

//	inherit from extendable (will allow adding observables/computables on client-side)
UserProfile.prototype = new extendable();

